In [2]:
import numpy as np

In [3]:
x = [1,2,3]
y = [4,5,6]
x + y

[1, 2, 3, 4, 5, 6]

In [10]:
B = np.array([[1,2,3], [4,5,6]])

In [5]:
B + 2*B

array([[ 3,  6,  9],
       [12, 15, 18]])

In [6]:
np.matmul(B.transpose(), B)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [12]:
B[1,2]

6

In [8]:
B[1,1]

5

In [11]:
B[1,:]

array([4, 5, 6])

In [13]:
B[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [14]:
B.shape

(2, 3)

In [15]:
vec = np.array([1,2,3])
print(vec)

[1 2 3]


In [122]:
class Array:
    "Una clase minima para algebra lineal"    
    def __init__(self, list_of_rows): 
        "Constructor"
        self.data = list_of_rows
        self.shape = (len(list_of_rows), len(list_of_rows[0]))
    def __repr__(self):
        return str(self.data)
    def __str__(self):
        return str(self.data)

In [17]:
A = Array([[1,2,3], [4,5,6]])
A.__dict__ # el campo escondido __dict__ permite acceder a las propiedades de clase de un objeto

{'data': [[1, 2, 3], [4, 5, 6]], 'shape': (2, 3)}

In [19]:
A.data

[[1, 2, 3], [4, 5, 6]]

In [21]:
A.shape

(2, 3)

In [22]:
Array([[1,2,3], [4,5,6]])

In [23]:
print(Array([[1,2,3], [4,5,6]]))

In [24]:
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
print(np.array([[1,2,3], [4,5,6]]))

[[1 2 3]
 [4 5 6]]


In [26]:
class TestClass:
    def __init__(self):
        pass # this means do nothing in Python
    def say_hi(self):
        print("Hey, I am just a normal method saying hi!")
    def __repr__(self):
        return "I am the special class method REPRESENTING a TestClass without printing"
    def __str__(self):
        return "I am the special class method for explicitly PRINTING a TestClass object"

In [27]:
x = TestClass()

In [28]:
x.say_hi()

Hey, I am just a normal method saying hi!


In [29]:
x

I am the special class method REPRESENTING a TestClass without printing

In [31]:
print(x)

I am the special class method for explicitly PRINTING a TestClass object


In [123]:
A = Array([[1,2,3], [4,5,6]])

In [124]:
A

[[1, 2, 3], [4, 5, 6]]

In [125]:
print(A)

[[1, 2, 3], [4, 5, 6]]


In [24]:
class Array:
    "Una clase minima para algebra lineal"    
    def __init__(self, list_of_rows): 
        "Constructor y validador"
        # obtener dimensiones
        self.data = list_of_rows
        nrow = len(list_of_rows)
        self.rango = nrow
        #  ___caso vector: redimensionar correctamente
        if not isinstance(list_of_rows[0], list):
            nrow = 1
            self.data = [[x] for x in list_of_rows]
        # ahora las columnas deben estar bien aunque sea un vector
        ncol = len(self.data[0])
        self.shape = (nrow, ncol)
        # validar tamano correcto de filas
        if any([len(r) != ncol for r in self.data]):
            raise Exception("Las filas deben ser del mismo tamano")
    def __repr__(self):
        Mtx=""
        for i in range(self.rango):
                Mtx=Mtx+str(self[i,:])
                if i<(self.rango)-1:
                    Mtx=Mtx+"\n"
        return (Mtx)
    def __str__(self):
        Mtx=""
        for i in range(self.rango):
                Mtx=Mtx+str(self[i,:])
                if i<(self.rango)-1:
                    Mtx=Mtx+"\n"
        return (Mtx)
    def __getitem__(self, idx):
        return self.data[idx[0]][idx[1]]
    def __setitem__(self, idx, new_value):
        self.data[idx[0]][idx[1]]= new_value
    def zeros(nrenglones,ncolumnas):
        matrizzero = Array([[0 for c in range(ncolumnas)]for r in range(nrenglones)])
        return matrizzero
    def eye(nrenglones,ncolumnas):
        matrizdiag = Array([[0 for c in range(ncolumnas)]for r in range(nrenglones)])
        for c in range (ncolumnas):
            for r in range (nrenglones):
                if c==r:
                    matrizdiag[c,r]=1
        return matrizdiag
    def transpose(self):
        nrow = len(self.data)
        ncol = len(self.data[0])
        
        MtrTrans= Array([[0 for c in range(nrow)]for r in range(ncol)])
        
        for r in range (nrow):
            for c in range (ncol):
                MtrTrans[c,r]= self.data[r][c]
        return MtrTrans           
    def __add__(self, other):
        "Hora de sumar"
        if isinstance(other, Array):
            if self.shape != other.shape:
                raise Exception("Las dimensiones son distintas!")
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] + other.data[r][c]
            return newArray
        elif isinstance(2, (int, float, complex)): # en caso de que el lado derecho sea solo un numero
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] + other
            return newArray
        else:
            return NotImplemented # es un tipo de error particular usado en estos metodos
    def __radd__(self,other):
        if other == 0:
            return self
        else:
            return self.__add__(other)
    def __sub__(self, other):
        if isinstance(other, Array):
            if self.shape != other.shape:
                raise Exception("Las dimensiones son distintas!")
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] - other.data[r][c]
            return newArray
        elif isinstance(2, (int, float, complex)): # en caso de que el lado derecho sea solo un numero
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] - other
            return newArray
        else:
            return NotImplemented # es un tipo de error particular usado en estos metodos
    def __mul__(self, other):
        if isinstance(other, Array):
            nrenA = len(self.data)
            ncolA = len(self.data[0])
            nrenB = len(other.data)
            ncolB = len (other.data[0])
            if ncolA != nrenB:
                raise Exception("Las matrices no se pueden multiplicar por no ser compatibles!")
            newArray = Array([[0. for c in range(ncolB)] for r in range(nrenA)])
            for i in range(nrenA):
                for j in range(ncolB):
                    for k in range (nrenB):
                        newArray[i,j]=newArray[i,j]+self.data[i][k]*other.data[k][j]
            return newArray
        elif isinstance(other,(int,float,complex)):
            rows,cols=self.shape
            newArray=Array([[0 for c in range(cols)]for r in range(rows)])
            for r in range (rows):
                for c in range (cols):
                    newArray.data[r][c]=self.data[r][c]*other
            return newArray
        else:
            return NotImplemented
    def __rmul__ (self,other):
        if isinstance(other,(int,float,complex)):
            rows, cols = self.shape
            newArray = Array([[0 for c in range(cols)]for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c]=self.data[r][c]*other
            return newArray
        else:
            return NotImplemented

In [128]:
vec = Array([1,2,3])
vec.data

[[1], [2], [3]]

In [7]:
A[1,0]

3

In [10]:
A[1,1]=8

In [33]:
print(A)

[1, 2]


In [8]:
A

[[1, 2], [3, 4], [7, 9], [8, 0]]

In [15]:
A.rango

4

In [32]:
B=Array([[1,2,3],[4,5,6]])

In [44]:
B

[[1, 2, 3], [4, 5, 6]]

In [46]:
B[0,1]

2

In [47]:
B[0,:]

[1, 2, 3]

In [21]:
A= Array

In [12]:
A.zeros(5,5)

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]

In [22]:
A.eye(5,5)

[1, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 1, 0, 0]
[0, 0, 0, 1, 0]
[0, 0, 0, 0, 1]

In [2]:
B=Array([[1,2,3],[4,5,6]])

In [33]:
B.transpose()

[1, 4]
[2, 5]
[3, 6]

In [34]:
B

[1, 2, 3]
[4, 5, 6]

In [3]:
B+1

[2, 3, 4]
[5, 6, 7]

In [4]:
1+B

[2, 3, 4]
[5, 6, 7]

In [5]:
B-1

[0, 1, 2]
[3, 4, 5]

In [7]:
A=Array([[11,12,13],[14,15,16]])

In [8]:
A-B

[10, 10, 10]
[10, 10, 10]

In [9]:
B-A

[-10, -10, -10]
[-10, -10, -10]

In [25]:
A=Array([[2,2],[3,3],[4,4]])

In [26]:
B=Array([[2,2,2],[3,3,3]])

In [22]:
A*B

[10.0, 10.0, 10.0]
[15.0, 15.0, 15.0]
[20.0, 20.0, 20.0]

In [23]:
A*5

[10, 10]
[15, 15]
[20, 20]

In [27]:
5*A

[10, 10]
[15, 15]
[20, 20]

In [28]:
B*A

[18.0, 18.0]
[27.0, 27.0]