In [1]:
class Array: 
    def __init__(self, list_of_rows): 
        "Constructor y validador"
        # obtener dimensiones
        self.data = list_of_rows
        nrow = len(list_of_rows)
        #  ___caso vector: redimensionar correctamente
        if not isinstance(list_of_rows[0], list):
            nrow = 1
            self.data = [[x] for x in list_of_rows]
        # ahora las columnas deben estar bien aunque sea un vector
        ncol = len(self.data[0])
        self.shape = (nrow, ncol)
        # validar tamano correcto de filas
        if any([len(r) != ncol for r in self.data]):
            raise Exception("Las filas deben ser del mismo tamaño")
    def __add__(self, other):
        "Hora de sumar"
        if isinstance(other, Array):
            if self.shape != other.shape:
                raise Exception("Las dimensiones son distintas!")
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] + other.data[r][c]
            return newArray
        elif isinstance(2, (int, float, complex)): # en caso de que el lado derecho sea solo un numero
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] + other
            return newArray
        else:
            return NotImplemented # es un tipo de error particular usado en estos metodos
    def __getitem__(self, idx):
        return self.data[idx[0]][idx[1]]
# EJERCICIO 1:            
    def __repr__(self):
        if self.shape[0]==1:
            msj='array('+str(self.data[0])+')'
            return msj
        else:
            msj=""
            for i in range(self.shape[0]):
                if i==0:
                    msj='array(['+str(self.data[0])
                else:
                    msj=str(msj)+'\n'+'\t'+ '   '+str(self.data[i])
            return msj+'])'
    
    def __str__(self):
        if self.shape[0]==1:
            msj='['+str(self.data[0]).replace(',','')+']'
            return msj
        else:
            msj=""
            for i in range(self.shape[0]):
                if i==0:
                    msj='['+str(self.data[0]).replace(',','')
                else:
                    msj=str(msj)+ '\n'+' '+str(self.data[i]).replace(',','')
            return msj+']'  
# EJERCICIO 2:      
    def __setitem__(self, idx, new_value):
        self.data[idx[0]][idx[1]]= new_value
        return self.data[idx[0]][idx[1]]
# EJERCICIO 3:   
    def zeros(shape):
        return Array([[0 for x in range(shape[1])] for y in range(shape[0])])
    def eye(n):
        b=zeros((n,n))
        for i in range(n):
            b[i,i]=1
        return b
# EJERCICIO 4: 
    def traspose(self):
        tt=zeros((self.shape[1],self.shape[0]))
        for i in range(self.shape[0]):
            for j in range(self.shape[1]):
               tt[j,i]=self.data[i][j]
        return tt
# EJERCICIO 5:
    def __radd__(self,other):
        if  isinstance(other, (int, float, complex)): 
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] + other
            return newArray
        else:
            return NotImplemented

    def __sub__(self,other):
        if isinstance(other, Array):
            if self.shape != other.shape:
                raise Exception("Las dimensiones son distintas!")
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] - other.data[r][c]
            return newArray
        elif isinstance(2, (int, float, complex)): # en caso de que el lado derecho sea solo un numero
            rows, cols = self.shape
            newArray = Array([[0. for c in range(cols)] for r in range(rows)])
            for r in range(rows):
                for c in range(cols):
                    newArray.data[r][c] = self.data[r][c] - other
            return newArray
        else:
            return NotImplemented
# EJERCICIO 6:    
    def __mul__(self,other):
        if isinstance(other, Array):
            if self.shape[1] != other.shape[0]:
                raise Exception("Las dimensiones no coinciden para multiplicar!")
            newArray = Array([[0. for c in range(other.shape[1])] for r in range(self.shape[0])])
            for r in range(self.shape[0]):
                for c in range(other.shape[1]):
                     for i in range(self.shape[1]):
                         newArray.data[r][c] = newArray.data[r][c] + (self.data[r][i] * other.data[i][c])
            return newArray
        else:
            return NotImplemented 
        
    def __rmul__(self,other):
        if  isinstance(other, (int, float, complex)): 
            newArray = Array([[0. for c in range(self.shape[0])] for r in range(self.shape[1])])
            for r in range(self.shape[0]):
                for c in range(self.shape[1]):
                    newArray.data[r][c] = self.data[r][c]*other
            return newArray
        else:
            return NotImplemented
        

class Vector(Array):
    def __init__(self, list_of_numbers):
        self.vdata = list_of_numbers
        list_of_rows = [[x] for x in list_of_numbers]
        return Array.__init__(self, list_of_rows)
    def __repr__(self):
        return "Vector(" + str(self.vdata) + ")"
    def __str__(self):
        return str(self.vdata)
    def __add__(self, other):
        new_arr = Array.__add__(self, other)
        return Vector([x[0] for x in new_arr.data])
    
# EJERCICIOS 7-10 (El gran final)

# Función forward_subs
    def forward_subs(self, other):
        if isinstance(other, Array):
            if self.shape[1] != other.shape[0]:
                raise Exception("Las dimensiones no coinciden para multiplicar!")
            newArray = Array([[0.] for r in range(self.shape[1])])   
            for r in range(self.shape[0]):
                newArray.data[r] = other.data[r]
                for c in range(r):
                    newArray.data[r][0] -= self.data[r][c] * newArray.data[c][0]
                newArray.data[r][0] /= self.data[r][r]
            return newArray
        else:
            return NotImplemented
        

# Función backward_subs
    def backward_subs(self, other):
        if isinstance(other, Array):
            if self.shape[1] != other.shape[0]:
                raise Exception("Las dimensiones no coinciden para multiplicar!")
            newArray = Array([[0.] for r in range(self.shape[1])])   
            for r in reversed(range(self.shape[0])):
                newArray.data[r] = other.data[r]
                for c in range(r+1,self.shape[1]):
                    newArray.data[r][0] -= self.data[r][c] * newArray.data[c][0]
                newArray.data[r][0] /= self.data[r][r]
            return newArray
        else:
            return NotImplemented  
            
        
#Función LU
    def LU(self):
        U = zeros(self.shape)
        L = eye(self.shape[0])
        P = eye(self.shape[0])
        for j in range(self.shape[0]):
            rmax = max(range(j, self.shape[0]), key=lambda i: abs(self.data[i][j]))
            if rmax != j:
                P.data[j], P.data[rmax] = P.data[rmax], P.data[j]
        newArray = P * self
        for j in range(self.shape[0]):
            for i in range(j+1):
                s1 = sum(U[k,j]*L[i,k] for k in range(i))
                U[i,j] = newArray[i,j] - s1
            for i in range(j,self.shape[0]):
                s2 = sum(U[k,j]*L[i,k] for k in range(j))
                L[i,j] = (newArray[i,j] - s2)/U[j,j]
        return (L,U,P)
    
    
#Función lu_linsolve
    def lu_linsolve(self,other):
        if isinstance(other, Array):
            if self.shape[1] != other.shape[0]:
                raise Exception("Las dimensiones no coinciden para resolver!")
            (L , U , P) = LU(self)
            y = forward_subs(L , P*other)
            x = backward_subs(U,y)
            return x
        

In [2]:
#PRUEBA EJERCICIO 1:
A=Array([[1,2,3],[4,5,6]])
A
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
#PRUEBA EJERCICIO 2:
A=Array([[1,2,3],[4,5,6]])
A[0,1]=7
print(A)

[[1 7 3]
 [4 5 6]]


In [4]:
# PRUEBA EJERCICIO 3 (FUNCIÓN ZEROS):

def zeros(shape):
    return Array([[0 for x in range(shape[1])] for y in range(shape[0])])
    
b=Array
print(b.zeros((6,2)))


[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [5]:
# PRUEBA EJERCICIO 3 (FUNCIÓN EYE)
def eye(n):
    b=zeros((n,n))
    for i in range(n):
        b[i,i]=1
    return b

t=Array
t=eye(3)
print(t)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
# PRUEBA EJERCICIO 4 (TRASPOSE):
A=Array([[1,2,3],[4,5,6]])
print(A.traspose())

[[1 4]
 [2 5]
 [3 6]]


In [7]:
# PRUEBA EJERCICIO 5 (SUMA POR LA DERECHA):
A = Array([[1,5], [4,4]])
B = Array([[7,9], [3,8]])
print(15+A)



[[16 20]
 [19 19]]


In [8]:
# PRUEBA EJERCICIO 5 (RESTA MATRICES):
A = Array([[1,5], [4,4]])
B = Array([[7,9], [3,8]])
print(A-B)

[[-6 -4]
 [1 -4]]


In [9]:
# PRUEBA EJERCICIO 6 (PRODUCTO MATRICES):
A = Array([[1,5], [4,4]])
B = Array([[7,9], [3,8]])
print(A*B)


[[22.0 49.0]
 [40.0 68.0]]


In [10]:
# PRUEBA EJERCICIO 6 (PRODUCTO MATRIZ POR ESCALAR):
A = Array([[1,5], [4,4]])
B = Array([[7,9], [3,8]])
print(5*A)

[[5 25]
 [20 20]]


In [11]:
# PRUEBA EJERCICIOS 7-10 (FUNCIÓN FORWARD_SUBS):
def traspose(self):
    tt=zeros((self.shape[1],self.shape[0]))
    for i in range(self.shape[0]):
        for j in range(self.shape[1]):
            tt[j,i]=self.data[i][j]
    return tt

def forward_subs(self, other):
    if isinstance(other, Array):
        if self.shape[1] != other.shape[0]:
            raise Exception("Las dimensiones no coinciden para multiplicar!")
        newArray = Array([[0.] for r in range(self.shape[1])])   
        for r in range(self.shape[0]):
            newArray.data[r] = other.data[r]
            for c in range(r):
                newArray.data[r][0] -= self.data[r][c] * newArray.data[c][0]
            newArray.data[r][0] /= self.data[r][r]
        return newArray
    else:
        return NotImplemented 

    #Para probar forward_subs
A = Array([[3,0,0,0], [-1,1,0,0], [3,-2,-1,0],[1,-2,6,2]])
b = Array([[5,6,4,2]])
print(forward_subs(A,traspose(b)))



[[1.6666666666666667]
 [7.666666666666667]
 [-14.333333333333334]
 [50.833333333333336]]


In [12]:
# PRUEBA EJERCICIOS 7-10 (FUNCIÓN BACKWARD_SUBS):
def traspose(self):
    tt=zeros((self.shape[1],self.shape[0]))
    for i in range(self.shape[0]):
        for j in range(self.shape[1]):
            tt[j,i]=self.data[i][j]
    return tt

def backward_subs(self, other):
    if isinstance(other, Array):
        if self.shape[1] != other.shape[0]:
            raise Exception("Las dimensiones no coinciden para multiplicar!")
        newArray = Array([[0.] for r in range(self.shape[1])])   
        for r in reversed(range(self.shape[0])):
            newArray.data[r] = other.data[r]
            for c in range(r+1,self.shape[1]):
                newArray.data[r][0] -= self.data[r][c] * newArray.data[c][0]
            newArray.data[r][0] /= self.data[r][r]
        return newArray
    else:
        return NotImplemented  
    
#Para probar backward_subs
A = Array([[4,-1,2,3],[0,-2,7,-4],[0,0,6,5],[0,0,0,3]])
b = Array([[20,-7,4,6]])
x=backward_subs(A,traspose(b))
print(x)

[[3.0]
 [-4.0]
 [-1.0]
 [2.0]]


In [13]:
# PRUEBA EJERCICIOS 7-10 (LUP):

def LU(self):
    U = zeros(self.shape)
    L = eye(self.shape[0])
    P = eye(self.shape[0])
    for j in range(self.shape[0]):
        rmax = max(range(j, self.shape[0]), key=lambda i: abs(self.data[i][j]))
        if rmax != j:
            P.data[j], P.data[rmax] = P.data[rmax], P.data[j]
    newArray = P * self
    for j in range(self.shape[0]):
        for i in range(j+1):
            s1 = sum(U[k,j]*L[i,k] for k in range(i))
            U[i,j] = newArray[i,j] - s1
        for i in range(j,self.shape[0]):
            s2 = sum(U[k,j]*L[i,k] for k in range(j))
            L[i,j] = (newArray[i,j] - s2)/U[j,j]
    return (L,U,P)

#Para probar LUP
A = Array([[4,2,3],[-3,1,4],[2,4,5]])
(L , U , P) = LU(A)
print(L)
print(U)
print(P)

[[1.0 0 0]
 [0.5 1.0 0]
 [-0.75 0.8333333333333334 1.0]]
[[4.0 2.0 3.0]
 [0 3.0 3.5]
 [0 0 3.333333333333333]]
[[1 0 0]
 [0 0 1]
 [0 1 0]]


In [14]:
# PRUEBA EJERCICIOS 7-10 (LU_LINSOLVE):
def lu_linsolve(self,other):
    if isinstance(other, Array):
        if self.shape[1] != other.shape[0]:
            raise Exception("Las dimensiones no coinciden para resolver!")
        (L , U , P) = LU(self)
        y = forward_subs(L , P*other)
        x = backward_subs(U,y)
        return x
    
#Para probar lu_linsolve
A = Array([[2,4,1],[4,-10,2],[1,2,4]])
b = Array([[5,-8,13]])
print(lu_linsolve(A,traspose(b)))

[[-1.0]
 [1.0]
 [3.0]]
